/** Shared shapes. Mirrors what the graph8 API returns; kept loose where the contract is loose. */

export type MetricStatus = "available" | "zero" | "stale" | "unknown" | "missing";

export interface EmailMetrics {
  sent: number;
  delivered: number;
  opened: number | null;
  replied: number;
  bounced: number;
  open_rate?: number | null;
  reply_rate?: number | null;
}

export interface CampaignMetrics {
  campaign_id: string;
  name: string;
  status: string;
  is_running: boolean;
  sequence_count: number;
  days: number;
  email_metrics: EmailMetrics | null;
  metrics_available: boolean;
  metric_status: MetricStatus;
  send_receipts: {
    dispatched: number;
    succeeded: number;
    last_dispatched_at: string | null;
  } | null;
  reconciliation: {
    rollup_sent: number;
    receipt_dispatched: number;
    receipt_succeeded: number;
    receipt_last_dispatched_at: string | null;
    discrepancy: boolean;
    note: string;
  };
  /** True when the numbers were generated by `autopilot seed --simulate`. Always surfaced in UI. */
  simulated?: boolean;
}

export interface CampaignSummary {
  id: string;
  name: string;
  status: string;
  category?: string | null;
  goal?: string | null;
  target_persona?: string | null;
  created_at?: string;
  primary_hook?: string | null;
  core_concept?: string | null;
}

export interface CampaignDocument {
  id: string;
  campaign_id: string;
  file_type: string;
  display_name: string;
  folder_path?: string;
  status?: string;
  updated_at?: string;
  content: string;
}

export interface SequenceStep {
  step_id: string;
  day: number;
  condition: unknown;
  stop_on_reply: boolean;
}

export interface StepCatalogEntry {
  step_id: string;
  name: string;
  channel: string;
  mode?: string;
  angle_id?: string;
  cta_type?: string;
  personalization_level?: string;
  constraints?: { max_words?: number };
  asset_ref?: string;
}

export interface CampaignFull extends CampaignSummary {
  channels?: string[];
  audience?: unknown;
  documents: CampaignDocument[];
  sequence: { campaign_id: string; version: string; created_at: string; steps: SequenceStep[] } | null;
  step_catalog: { steps: Record<string, StepCatalogEntry> } | null;
  linked_sequences: Array<{ id?: string | number; sequence_id?: string | number; name?: string }>;
  is_launched: boolean;
}

export interface StepMetrics {
  step_id: string;
  sent: number;
  delivered?: number;
  replied: number;
  bounced?: number;
}

export type ReplyClass =
  | "positive"
  | "objection"
  | "not_now"
  | "ooo"
  | "unsubscribe"
  | "wrong_person"
  | "bounce_notice";

export interface InboxThread {
  id: string;
  contact?: { name?: string; email?: string; title?: string; company?: string };
  preview?: string;
  subject?: string;
  sequence_id?: string | number | null;
  campaign_id?: string | null;
  received_at?: string;
  status?: string;
  tags?: string[];
}

export interface DeliverabilityInfo {
  safe_to_send?: unknown;
  degraded_mailboxes?: unknown[];
  sequences_health?: unknown;
  metrics?: unknown;
}

/** One campaign's worth of collected data, written to data/snapshots/<ts>/<campaign_id>.json */
export interface CampaignSnapshot {
  collected_at: string;
  campaign: CampaignSummary;
  full: CampaignFull | null;
  metrics: CampaignMetrics | null;
  step_metrics: StepMetrics[];
  replies: InboxThread[];
  deliverability_risk: { degraded: boolean; reasons: string[] };
  simulated?: boolean;
}
